-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQlFwsDAPLj0tPMUE
hPCxoEfopcjV1bDeXjvDS8kblYCgCgYIKoZIzj0DAQehRANCAATFIiJ+q05eUZO0
xwNvOy6YbFTNGw10h/Xws77VICokK3JYFFP73SFJFiLGJoDiBvYtxszbgR9TZHyN
hE70sCHQ
-----END PRIVATE KEY-----